GET http://localhost:5000/cards

###
GET http://localhost:5000/cards/5de1bb95acebae1ee4beae3e

###

POST http://localhost:5000/cards
Content-Type: application/json

{
  "name": "Quadra",
  "description": "An API spell card, concerning a command to replicate a spell's effects 4 times"
}

###
PATCH http://localhost:5000/cards/5de1bfc8c891d63d948d1c8c
Content-Type: application/json

{
  "name": "Alpha 2.0 Name"
}

###
DELETE http://localhost:5000/cards/5de2ff5cbd31793980a4e805